import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Gnb from "@/components/Gnb";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DO IT",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-small.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="page">
          <Gnb />
          {children}
        </div>
      </body>
    </html>
  );
}
