import type { Metadata } from "next";
import Gnb from "@/components/Gnb";
import "./globals.css";

export const metadata: Metadata = {
  title: "DO IT",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-small.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto flex max-w-[1000px] flex-col px-[15px]">
        <div>
          <Gnb />
          {children}
        </div>
      </body>
    </html>
  );
}
